services:
  
  # Frontend service
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile

    container_name: unisync_frontend
    ports:
      -"3000:3000"
    
    environment:
      - REACT_APP_API_url=http://localhost:5000
    restart: unless_stopped
    depends_on:
      -backend

    

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: unisync_backend
    ports: "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://unisync_user:unisync_password@postgres:5432/unisync_db
      - AI_SERVICE_URL=http://ai-service:8000

    restart: unless_stopped
    depends_on:
      postgres:
        condition: service_healty
      ai-service: 
        condition: service started


  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: unisync-ai
    ports:
      -"8000:8000"

    volumes:
      - ./ai-service:/app
      - huggingface_cache:/root/.cache/huggingface_cache



  postgres:
    image: postgres:16-alpine
    container_name: unisync_postgres
    
    ports:
      - "5432:5432"

    environment:
      
      


